general:
  verbose: true
  
steps:
  mtaBuild:
    buildTarget: 'CF'
  dockerExecuteOnKubernetes:
    securityContext:
      runAsUser: 1000480000
      fsGroup: 0
      allowPrivilegeEscalation: true

