general:
  verbose: true

steps:
  pipelineExecute:
    repoUrl: 'https://github.com/Alliander/SCP-pipelines.git'
    branch: 'WIP'
    path: 'WIP/Jenkinsfile'
    credentialsId: 'svc-jenkins-github'
    
  artifactSetVersion:
    gitSshUrl: 'git@github.com:redejong-72/test-osc.git'
    gitCommitId: ''
    commitVersion: false
  mtaBuild:
    buildTarget: 'CF'
  influxWriteData:
    influxServer: influxDB
  sonarExecuteScan:
    instance: SonarCubeSPT
    dockerImage: newtmitch/sonar-scanner
    options: '-Dsonar.projectBaseDir=$WORKSPACE -Dsonar.analysis.mode=publish -Dsonar.scanner.metadataFilePath=$WORKSPACE/report-task.txt'
