general:
  verbose: true
  CREDENTIAL_ID: svc-jenkins-github
  JENKINSFILE_GIT_URL: 'https://github.com/Alliander/SCP-pipelines'
  JENKINSFILE_GIT_BRANCH: WIP
  JENKINSFILE_PATH: WIP/Jenkinsfile

steps:
  artifactSetVersion:
    gitSshUrl: 'git@github.com:redejong-72/test-osc.git'
    gitCommitId: ''
    commitVersion: false
  mtaBuild:
    buildTarget: 'CF'
  influxWriteData:
    influxServer: influxDB
  sonarExecuteScan:
    instance: SonarCubeSPT
    dockerImage: newtmitch/sonar-scanner
    options: '-Dsonar.projectBaseDir=$WORKSPACE -Dsonar.analysis.mode=publish -Dsonar.scanner.metadataFilePath=$WORKSPACE/report-task.txt'
