general:
  verbose: true
  
steps:
  mtaBuild:
    buildTarget: 'CF'
  dockerExecuteOnKubernetes:
    securityContext:
      runAsUser: 1000480000
      runAsGroup: 1000480000
      fsGroup: 1000480000
      allowPrivilegeEscalation: true
      seLinuxOptions:
       level: 's0-s0:c0.c1023'

