general:
  verbose: true
  dockerExecuteOnKubernetes:
    securityContext:
      runAsUser: 1000480000
      runAsGroup: 1000480000
      fsGroup: 1000480000
steps:
  mtaBuild:
    buildTarget: 'CF'

