general:
  verbose: true

steps:  
  artifactSetVersion:
    gitSshUrl: 'git@github.com:redejong-72/test-osc.git'
    gitCommitId: ''
    commitVersion: false
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry/org: alliander-cf-tst
    cloudFoundry/space: 'CI'
    cloudFoundry/credentialsId: cf-jenkins
    deploytool: mtaDeployPlugin
    credentials
  influxWriteData:
    influxServer: influxDB
  sonarExecuteScan:
    instance: SonarCubeSPT
    dockerImage: newtmitch/sonar-scanner
    options: '-Dsonar.projectBaseDir=$WORKSPACE -Dsonar.analysis.mode=publish -Dsonar.scanner.metadataFilePath=$WORKSPACE/report-task.txt'
