general:
  verbose: true
  JenkinsFileGitUrl: 'https://github.com/Alliander/SCP-pipelines.git'
  JenkinsFileGitBranch: WIP
  JenkinsFilePath: 'WIP/Jenkinsfile'
  JenkinsFileGitCredentialId: 'svc-jenkins-github'

steps:  
  artifactSetVersion:
    gitSshUrl: 'git@github.com:redejong-72/test-osc.git'
    gitCommitId: ''
    commitVersion: false
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: standard
    cloudFoundry:
      org: 'Alliander-tst-cf'
      space: 'CI'
      credentialsId: cf-jenkins
  influxWriteData:
    influxServer: influxDB
  sonarExecuteScan:
    instance: SonarCubeSPT
    dockerImage: newtmitch/sonar-scanner
    options: '-Dsonar.projectBaseDir=$WORKSPACE -Dsonar.analysis.mode=publish -Dsonar.scanner.metadataFilePath=$WORKSPACE/report-task.txt'
stages:
  artifactDeployment:
    nexusConfiguration:
      url: 'https://nexus.alliander.local'
      repository: 'SCP-releases'
      version: 3
      credentialsId: svc-jenkins-to-nexus
      groupId: GROUP
